export const ROLES = {
  ADMIN: 'ADMIN',
  CAIXA: 'CAIXA',
  GARCON: 'GARCON',
  COZINHEIRO: 'COZINHEIRO',
};

export const ADMIN_ROLES = [ROLES.ADMIN];
export const CAIXA_ROLES = [ROLES.ADMIN, ROLES.CAIXA];
export const GARCON_ROLES = [ROLES.ADMIN, ROLES.GARCON];
export const COZINHEIRO_ROLES = [ROLES.ADMIN, ROLES.COZINHEIRO];